server:
  port: 8082
grpc:
  port: 6569
mail:
  from: phamhoangnamuet.vnu@gmail.com
  from-name: hoangnam
  smtp:
    username: phamhoangnamuet.vnu@gmail.com
    host: smtp.gmail.com
    password: hoangnampltn
    port: 25
  verification-api: http://localhost:8080/verifying-email?token=

mongo:
  remoteUri: "mongodb+srv://web-server:server123@cluster0.tmzfq.mongodb.net/user-service?retryWrites=true&w=majority"

